// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScraperDAL;

namespace ScraperRepositories.Migrations
{
    [DbContext(typeof(ScrapersContext))]
    [Migration("5_Add_DataKomo")]
    partial class Komo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ScraperModels.Models.Db.AdItemHomeLessDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdItemId");

                    b.Property<string>("Address");

                    b.Property<string>("AgencyName");

                    b.Property<string>("City");

                    b.Property<string>("Contact");

                    b.Property<string>("DateUpdated");

                    b.Property<string>("Description");

                    b.Property<string>("Field0");

                    b.Property<string>("Field1");

                    b.Property<string>("Field2");

                    b.Property<string>("Field3");

                    b.Property<string>("Field4");

                    b.Property<string>("Field5");

                    b.Property<string>("Field6");

                    b.Property<string>("Floor");

                    b.Property<string>("Latitude");

                    b.Property<string>("LinkToProfile");

                    b.Property<string>("Longitude");

                    b.Property<string>("Phone");

                    b.Property<string>("Phone1");

                    b.Property<string>("Phone2");

                    b.Property<string>("Region");

                    b.Property<string>("Size");

                    b.HasKey("Id");

                    b.ToTable("DataHomeLess");
                });

            modelBuilder.Entity("ScraperModels.Models.Db.AdItemKomoDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdItemId");

                    b.Property<string>("CheckHour");

                    b.Property<string>("ContactName");

                    b.Property<string>("Description");

                    b.Property<string>("Extras");

                    b.Property<string>("Floor");

                    b.Property<string>("Latitude");

                    b.Property<string>("Longitude");

                    b.Property<string>("Phone1");

                    b.Property<string>("Phone2");

                    b.Property<string>("Price");

                    b.Property<string>("PropertyType");

                    b.Property<string>("Rooms");

                    b.Property<string>("Square");

                    b.Property<string>("Updated");

                    b.HasKey("Id");

                    b.ToTable("DataKomo");
                });

            modelBuilder.Entity("ScraperModels.Models.Db.AdItemOnmapDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdItemId");

                    b.Property<string>("AriaBase");

                    b.Property<string>("Balconies");

                    b.Property<string>("Bathrooms");

                    b.Property<string>("ContactEmail");

                    b.Property<string>("ContactName");

                    b.Property<string>("ContactPhone");

                    b.Property<string>("DateCreate");

                    b.Property<string>("DateUpdate");

                    b.Property<string>("Description");

                    b.Property<string>("Elevators");

                    b.Property<string>("EnCity");

                    b.Property<string>("EnHouseNumber");

                    b.Property<string>("EnNeighborhood");

                    b.Property<string>("EnStreetName");

                    b.Property<string>("FloorOf");

                    b.Property<string>("FloorOn");

                    b.Property<string>("HeCity");

                    b.Property<string>("HeHouseNumber");

                    b.Property<string>("HeNeighborhood");

                    b.Property<string>("HeStreetName");

                    b.Property<string>("Latitude");

                    b.Property<string>("Longitude");

                    b.Property<string>("Price");

                    b.Property<string>("PropertyType");

                    b.Property<string>("Rooms");

                    b.Property<string>("Section");

                    b.Property<string>("Toilets");

                    b.HasKey("Id");

                    b.ToTable("DataOnmap");
                });

            modelBuilder.Entity("ScraperModels.Models.Db.AdItemWinWinDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdItemId");

                    b.Property<string>("AmountPayment");

                    b.Property<string>("Area");

                    b.Property<string>("City");

                    b.Property<string>("ContactName");

                    b.Property<string>("DateEnter");

                    b.Property<string>("DateUpdate");

                    b.Property<string>("Description");

                    b.Property<string>("Floor");

                    b.Property<string>("IsAgent");

                    b.Property<string>("IsPartners");

                    b.Property<string>("Latitude");

                    b.Property<string>("Longitude");

                    b.Property<string>("Phone1");

                    b.Property<string>("Phone2");

                    b.Property<string>("Price");

                    b.Property<string>("Rooms");

                    b.Property<string>("Square");

                    b.Property<string>("State");

                    b.Property<string>("StreetAddress");

                    b.HasKey("Id");

                    b.ToTable("DataWinWin");
                });

            modelBuilder.Entity("ScraperModels.Models.Db.AdItemYad2DbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdItemId");

                    b.Property<string>("AirConditioner");

                    b.Property<string>("AriaBase");

                    b.Property<string>("Balconies");

                    b.Property<string>("ContactEmail");

                    b.Property<string>("ContactName");

                    b.Property<string>("ContactPhone");

                    b.Property<string>("DateCreate");

                    b.Property<string>("DateUpdate");

                    b.Property<string>("Description");

                    b.Property<string>("Elevators");

                    b.Property<string>("FloorOf");

                    b.Property<string>("FloorOn");

                    b.Property<string>("HeCity");

                    b.Property<string>("HeHouseNumber");

                    b.Property<string>("HeNeighborhood");

                    b.Property<string>("HeStreetName");

                    b.Property<List<string>>("Images");

                    b.Property<string>("Latitude");

                    b.Property<string>("Longitude");

                    b.Property<string>("Parking");

                    b.Property<string>("Pets");

                    b.Property<string>("Price");

                    b.Property<string>("PropertyType");

                    b.Property<string>("Rooms");

                    b.HasKey("Id");

                    b.ToTable("DataYad2");
                });
#pragma warning restore 612, 618
        }
    }
}
